###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"JORGE",
    "age":"33",
    "email":"Ney0@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1




###

PUT http://localhost:9000/api/users/663050dbce4bb4b066cfd4cd HTTP/1.1
Content-Type: application/json

{
    "name":"JORGE gab",
    "age":"33",
    "email":"Ney0@gmail.com"
}

###
DELETE http://localhost:9000/api/users/66305825e590242760527577 HTTP/1.1